### ISSUE TITLE
Checklist for release

### ISSUE THREAD

**Issue by supersimple** [hexpm/preview#3]
## Required
* [x] Add rollbar (https://github.com/hexpm/preview/pull/4)
* [x] Add logster (see hexpm) (https://github.com/hexpm/preview/pull/7)
* [x] Add mix release (https://github.com/hexpm/preview/pull/8)
* [x] Dockerfile + google cloud build (see hexpm/cloudbuild.yaml) (https://github.com/hexpm/preview/pull/8)
* [x] Add to https://github.com/hexpm/hexpm-ops (terraform and kubernetes)
  * [x] Staging (https://github.com/hexpm/hexpm-ops/pull/44/files)
  * [x] Prod
* [x] Add license (https://github.com/hexpm/preview/pull/5)
* [x] Add ENV VARs: PREVIEW_BUCKET, HEXDOCS_GCP_CREDENTIALS, PREVIEW_ROLLBAR_ACCESS_TOKEN
* [x] implement Bucket.get_file_list/2 for local

## Nice to have
* [x] Change default branch to _main_
* [ ] More tests =)
* [ ] Review design

## After release
* [ ] Link from https://hex.pm package pages
* [ ] Deploy hexpm with above links
* [ ] Blog post and announce
